# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: XenWayne's Blog
subtitle: '寸进具欢喜，万物皆可爱。'
description: 'Web/摄影/全沾工程师🤣/音游人/平面设计/技术宅/LLer/假的车万人/柚子厨/PGP 0x0C7969C9'
keywords: XenWayne,Blog,Mevisual,LightZone
author: XenWayne
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://xenwayne.top
permalink: posts/:abbrlink/ 
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:  # 跳过渲染
  - "project/**/*.html"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/XenWayne/Blog
  branch: pages

# abbrlink config
abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: hex        #support dec(default) and hex
  drafts: false   #(true)Process draft,(false)Do not process draft. false(default) 
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true  #true(default)
     depth:        #3(default)
     over_write: false 
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink. This only updates abbrlink rather than other front variables..

# hexo-oh-my-live2d 配置
OhMyLive2d:
  enable: true
  CDN: https://unpkg.com/oh-my-live2d@latest
  # CDN: https://registry.npmmirror.com/oh-my-live2d/0.16/files/dist/index.min.js
  option:
    dockedPosition: 'left' # 模型停靠位置 默认值: 'right' 可选值: 'left' | 'right'
    # importType: 'cubism2' #  导入类型, 默认使用全量导入: complete , 可选值: complete, cubism2, cubism5
    libraryUrls: # 自定义 Cubism SDK 外部资源地址
      complete: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/complete.js
      cubism2: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/cubism2.js
      cubism5: https://registry.npmmirror.com/oh-my-live2d/latest/files/lib/cubism5.js

    menus: 
      items: |
        (defaultItems)=>{
        return [
          defaultItems[0],
          defaultItems[3]
        ]
        }
    # menus: |
    #   (currentModel) =>{
    #     console.log(currentModel);
    #   }
    # menus:
    # items: |
    #   (defaultItems)=>{
    #    return [
    #      ...defaultItems,
    #      {
    #        id: 'github',
    #        icon: 'github-fill',
    #        title: '我的github',
    #        onClick: ()=>window.open('https://github.com/hacxy')
    #      }
    #    ]
    #   }

    # items:
    #   - id: 'github'
    #     icon: 'github-fill'
    #     title: '我的github'
    #     onClick: ()=>window.open('https://github.com/hacxy')

    mobileDisplay: false # 是否在移动端显示
    models:
      # !snowmiku
      # - path: https://gcore.jsdelivr.net/gh/XenWayne/sitefile/live2d/snow_miku/model.json
      #   mobilePosition: [-20, 0] # 移动端时模型在舞台中的位置。 默认值: [0,0] [横坐标, 纵坐标]
      #   mobileScale: 0.07 # 移动端时模型的缩放比例 默认值: 0.1
      #   mobileStageStyle: # 移动端时舞台的样式
      #     width: 180
      #     height: 180
      #   motionPreloadStrategy: IDLE # 动作预加载策略 默认值: IDLE 可选值: ALL | IDLE | NONE
      #   position: [-20,0] # 模型在舞台中的位置。 默认值: [0,0] [横坐标, 纵坐标]
      #   scale: 0.075 # 模型的缩放比例 默认值: 0.1
      #   # showHitAreaFrames: false # 是否显示点击区域 默认值: false
      #   stageStyle:
      #     width: 250
      #     height: 250
      # !cdn-chino
      # - path: https://gcore.jsdelivr.net/gh/XenWayne/sitefile/live2d/chino/model.json
      #   mobilePosition: [-20, 0] # 移动端时模型在舞台中的位置。 默认值: [0,0] [横坐标, 纵坐标]
      #   mobileScale: 0.07 # 移动端时模型的缩放比例 默认值: 0.1
      #   mobileStageStyle: # 移动端时舞台的样式
      #     width: 180
      #     height: 180
      #   motionPreloadStrategy: IDLE # 动作预加载策略 默认值: IDLE 可选值: ALL | IDLE | NONE
      #   position: [16,15] # 模型在舞台中的位置。 默认值: [0,0] [横坐标, 纵坐标]
      #   scale: 0.17 # 模型的缩放比例 默认值: 0.1
      #   # showHitAreaFrames: false # 是否显示点击区域 默认值: false
      #   stageStyle:
      #     width: 250
      #     height: 250
      # !cdn-dujiaoshou_6
      - path: https://sitefile.xenwayne.top/https://raw.githubusercontent.com/XenWayne/sitefile/master/live2d/dujiaoshou_6/dujiaoshou_6.model3.json
        mobilePosition: [0, 0] # 移动端时模型在舞台中的位置。 默认值: [0,0] [横坐标, 纵坐标]
        mobileScale: 0.07 # 移动端时模型的缩放比例 默认值: 0.1
        mobileStageStyle: # 移动端时舞台的样式
          width: 150
          height: 150
        motionPreloadStrategy: IDLE # 动作预加载策略 默认值: IDLE 可选值: ALL | IDLE | NONE
        position: [-140,-8] # 模型在舞台中的位置。 默认值: [0,0] [横坐标, 纵坐标]
        scale: 0.06 # 模型的缩放比例 默认值: 0.1
        # showHitAreaFrames: false # 是否显示点击区域 默认值: false
        stageStyle:
          width: 250
          height: 400

          
    parentElement: document.body #为组件提供一个父元素，如果未指定则默认挂载到 body 中
    primaryColor: 'var(--btn-bg)' # 主题色 支持变量
    sayHello: false # 是否在初始化阶段打印项目信息
    tips:
      style:
        width: 200
        height: 100
        left: 50%
        top: -60px
      mobileStyle:
        width: 180
        height: 80
        left: 50%
        top: -100px
      idleTips:
        interval: 15000
        # message:
        #   - 你好呀~
        #   - 欢迎来到我的小站~
        # 自定义提示语 需要 引入 axios 库 ,也可以使用其他方法
        message:
        # wordTheDay: true
        # 自定义  https://v1.hitokoto.cn  数据
        # wordTheDay: |
        #   function(wordTheDayData){
        #     return `${wordTheDayData.hitokoto}    by.${wordTheDayData.from}`;
        #   }
  # 具体方法请看: https://oml2d.com/guide/loadModel.html#oml2d-%E5%AE%9E%E4%BE%8B
  # then: |
  #    oml2d.onStageSlideIn(() => {
  #    oml2d.tipsMessage('Oh My Live2D !!!', 3000, 10);
  #    });

# hexo-generator-sitemap
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  template: ./template_sitemap/sitemaptemp.xml
  template_txt: ./template_sitemap/sitemaptemp.txt
  rel: false
  tags: true
  categories: true

# hexo-filter-nofollow
nofollow:
  enable: true
  field: site
  exclude:
    - 'xenwayne.top'
    - 'www.xenwayne.top'
    - 'beta.xenwayne.top'
    - 'lightzone.mevisual.com'
    - 'mevisual.com'
    - 'www.mevisual.com'

# !hexo-artitalk-static
artitalk:
  enable: true
  title: 说说 | Essay ## 标题
  path: essay/index.html ## 生成路径
  pageSize: 20 ## 显示几条说说
  avatar: https://gcore.jsdelivr.net/gh/XenWayne/sitefile/img/avatar.webp ## 说说头像
  plugins: [] ## 插件，具体请看下文
  template: ## 说说模板，可查看仓库中的 main.ejs
  imports: ## 在说说模板的开头和结尾处插入内容
    before:
      - <p>这里是一些碎碎念，又或是一些过于简短不能形成文章的想法和回忆录，亦或是一些情绪垃圾。</p>
      - <p>一般不emo也不会来这写东西= =</p>
      - <p>Just take it easy.</p>
      - <p>Generated by <a href="https://github.com/Lete114/hexo-artitalk-static">hexo-artitalk-static</a>.</p>
      - <hr>
    after: 
      -
    # - <link rel="stylesheet" href="/css/index.css">
    # - '<style>body{color: red}</style>' ## 注意由于css的‘{}’是关键符号所以需要(单/双)引号''
    # - <script>alert(1)</script>

# !hexo-bilibili-bangumi
bangumi: # 追番设置
  enable: true
  source: bgmv0
  bgmInfoSource: 'bgmApi'
  path: /bangumi/index.html
  # vmid: 519493 #bgm api使用用户id
  vmid: xenwayne #bgmv0 api使用用户名
  title: '追番 | Bangumi'
  quote: '
  简单记录，成分鉴定器，乐意看点工业糖精= =，该页面数据可能不会及时更新。<br>
  Generated by <a href="https://github.com/HCLonely/hexo-bilibili-bangumi">hexo-bilibili-bangumi</a> 
  | Data From <a href="https://bgm.tv/user/xenwayne">bgm.tv</a>
  '
  show: 1
  lazyload: false
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading:
  showMyComment: true
  pagination: false
  metaColor:
  color:
  webp: true
  progress: true
  progressBar: true
  extraOrder:
  order: latest
  proxy:
    host: ''
    port: ''
  extra_options:
    key: value
  coverMirror:
game: # 游戏设置，仅支持source: bgmv0
  enable: true
  path: /gamelist/index.html
  source: bgmv0
  vmid: xenwayne
  title: '游戏 | Gamelist'
  quote: '
  简单记录，成分鉴定器，该页面数据可能不会及时更新。<br>
  Generated by <a href="https://github.com/HCLonely/hexo-bilibili-bangumi">hexo-bilibili-bangumi</a> 
  | Data From <a href="https://bgm.tv/user/xenwayne">bgm.tv</a>
  '
  show: 1
  lazyload: false
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading:
  metaColor:
  color:
  webp: true
  progress: true
  extraOrder:
  order: latest
  extra_options:
    key: value
  coverMirror:
cinema: # 追剧设置 # //禁用
  enable: false
  path:
  vmid:
  title: '追剧列表'
  quote: '生命不息，追剧不止！'
  show: 1
  lazyload: true
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading:
  metaColor:
  color:
  webp: true
  progress:
  extraOrder:
  order:
  extra_options:
    key: value
  coverMirror:



# Feed
feed:
  enable: true
  type: 
    - atom
    - rss2
  path: 
    - feed/atom.xml
    - feed/rss2.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  autodiscovery: true
  template: 

# !pdf-tag
pdf:
  enable: true          # default: true
  width: '100%'         # default: 100%
  height: '1200px'      # default: 550px

# !hexo-album-page
album:
  enable: true # 是否启用相册插件
  site_title: "影集 | Album | XenWayne's Blog" # 相册页面的标题
  favicon: '' # 站点图标
  output_path: album/index.html # 相册页面的渲染输出路径 
